name: Compile EmperorFox

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant Execute Permission to Gradle
        working-directory: ./fenix
        run: chmod +x ./gradlew

      - name: Bulletproof Nimbus Injector
        run: |
          mkdir -p ./fenix/build/bin/nimbus/125.20240317050356/
          
          if curl --fail -L -o ./fenix/nimbus-fml.zip "https://firefox-ci-tc.services.mozilla.com/api/index/v1/task/project.application-services.v2.nimbus-fml.latest/artifacts/public/build/nimbus-fml-x86_64-unknown-linux-gnu.zip"; then
            unzip -o -j ./fenix/nimbus-fml.zip -d ./fenix/build/bin/nimbus/125.20240317050356/
          else
            git clone --depth 1 https://github.com/mozilla/application-services.git app-services-src
            cd app-services-src
            cargo build --release -p nimbus-fml
            cp target/release/nimbus-fml ../fenix/build/bin/nimbus/125.20240317050356/
            cd ..
          fi
          
          chmod +x ./fenix/build/bin/nimbus/125.20240317050356/nimbus-fml

      - name: Compile EmperorFox APK
        working-directory: ./fenix
        run: ./gradlew app:assembleDebug --stacktrace --max-workers=2

      - name: Upload EmperorFox APK
        uses: actions/upload-artifact@v4
        with:
          name: EmperorFox-Android
          path: fenix/app/build/outputs/apk/debug/*.apk
