name: Compile EmperorFox

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant Execute Permission to Gradle
        working-directory: ./fenix
        run: chmod +x ./gradlew

      - name: Time-Travel Nimbus Injector
        run: |
          mkdir -p ./fenix/build/bin/nimbus/125.20240317050356/
          
          # Clone the Mozilla tools repo
          git clone https://github.com/mozilla/application-services.git app-services-src
          cd app-services-src
          
          # Rewind the repository exactly to March 17, 2024
          git checkout $(git rev-list -n 1 --before="2024-03-18 00:00" main)
          
          # Fetch the missing submodule dependencies
          git submodule update --init --recursive
          
          # Build the historically accurate version of the tool
          cargo build --release -p nimbus-fml
          
          # Inject it into your build folder
          cp target/release/nimbus-fml ../fenix/build/bin/nimbus/125.20240317050356/
          cd ..
          chmod +x ./fenix/build/bin/nimbus/125.20240317050356/nimbus-fml

      - name: Compile EmperorFox APK
        working-directory: ./fenix
        run: ./gradlew app:assembleDebug --stacktrace --max-workers=2

      - name: Upload EmperorFox APK
        uses: actions/upload-artifact@v4
        with:
          name: EmperorFox-Android
          path: fenix/app/build/outputs/apk/**/*.apk
